[package]
name = "web_scrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.20", features = ["blocking"] }
scraper = "0.23.1"
tokio = { version = "1.45.1", features = ["full"] }
